blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/forwardnetworks/forwardnetworks.github.io/security/policy
    about: Please report vulnerabilities privately.
